
# These constants are defined in libsshbouncer sshtrace_events.h and mapped to strings in event_serializer.cpp
SSHTRACE_EVENT_NEW_CONNECTION = 'connection_new'
SSHTRACE_EVENT_ESTABLISHED_CONNECTION = 'connection_established'
SSHTRACE_EVENT_CLOSE_CONNECTION = 'connection_close'
SSHTRACE_EVENT_COMMAND_START = 'command_start'
SSHTRACE_EVENT_COMMAND_END = 'command_finish'
SSHTRACE_EVENT_TERMINAL_UPDATE = 'terminal_update'
SSHTRACE_EVENT_FILE_UPLOAD = 'file_upload'

SSHTRACE_ALL_EVENTS = [
    SSHTRACE_EVENT_NEW_CONNECTION,
    SSHTRACE_EVENT_ESTABLISHED_CONNECTION,
    SSHTRACE_EVENT_CLOSE_CONNECTION,
    SSHTRACE_EVENT_COMMAND_START,
    SSHTRACE_EVENT_COMMAND_END,
    SSHTRACE_EVENT_TERMINAL_UPDATE,
    SSHTRACE_EVENT_FILE_UPLOAD
]